"""empty message

Revision ID: 113fb9504bf9
Revises: cb98ee7e6293
Create Date: 2022-10-17 15:59:37.574353

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '113fb9504bf9'
down_revision = 'cb98ee7e6293'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('permits', sa.String(length=128), nullable=True))
    op.drop_column('users', 'auth_level')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('auth_level', sa.SMALLINT(), autoincrement=False, nullable=False))
    op.drop_column('users', 'permits')
    # ### end Alembic commands ###
