"""empty message

Revision ID: cb98ee7e6293
Revises: 7607fdb6286a
Create Date: 2022-10-14 23:30:13.847655

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb98ee7e6293'
down_revision = '7607fdb6286a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('img', sa.String(length=256), nullable=True))
    op.drop_column('users', 'has_img')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('has_img', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('users', 'img')
    # ### end Alembic commands ###
