"""empty message

Revision ID: ecc9253f97d2
Revises: 113fb9504bf9
Create Date: 2022-10-17 17:19:20.674763

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ecc9253f97d2'
down_revision = '113fb9504bf9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('refresh_token', sa.String(length=256), nullable=True))
    op.create_unique_constraint(None, 'users', ['refresh_token'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'refresh_token')
    # ### end Alembic commands ###
