"""empty message

Revision ID: 332be269ffda
Revises: ecc9253f97d2
Create Date: 2022-10-18 13:14:32.886548

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '332be269ffda'
down_revision = 'ecc9253f97d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('img_url', sa.String(length=256), nullable=True))
    op.drop_column('users', 'img')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('img', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    op.drop_column('users', 'img_url')
    # ### end Alembic commands ###
